project:
  type: book
  output-dir: docs
  preview:
    port: 4200
    browser: true
  # resources: 
  #   - codebooks/ #Add codebooks to docs

book:
  title: "Old Notes, Musings, and Miscellany"
  author: "Andrew Zieffler"
  date: today
  page-navigation: false
  bread-crumbs: false
  sidebar:
    search: true
    background: '#001D3D'
  chapters:
    - index.qmd
    - 01-intro.qmd
    - 02-creating-tables.qmd
    - 02-01-latex-tables.qmd
    - 04-kde.qmd
    - 05-exploration.qmd
language:
  section-title-appendices: "Appendices"
bibliography: ["assets/musings.bib"]
csl: 'assets/apa-single-spaced.csl'

format:
  html:
    theme: 
      - cosmo
      - "assets/theme.scss"
    #css: ["assets/table-styles.css"] #"assets/style.css", , "assets/syntax.css", "assets/navbar.css"]
    header-includes: |
      <link rel="preconnect" href="https://fonts.googleapis.com">
      <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
      <link href="https://fonts.googleapis.com/css2?family=Atkinson+Hyperlegible:ital,wght@0,400;0,700;1,400;1,700&display=swap" rel="stylesheet">
    code-copy: true
    code-overflow: wrap
    highlight-style: 'a11y-dark'
    mainfont: 'Atkinson Hyperlegible'
    fontsize: '13pt'
    linestretch: '1.5em'
    linkcolor: '#A4508B' #'#7d12ba'
    toc: false
    toc-title: "On This Page"
    tbl-cap-location: "top"
    html-table-processing: none
    fig-cap-location: "top"
editor: source

